name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: install dependency
        run: make install
      - name: run lint
        run: make lint
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: install dependency
        run: make install
      - name: run tests
        run: make test
  coverage:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: install dependency
        run: make install
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
