name: Node.js CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repositorie
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: NPM install
        run: make install
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true